## Week 2 - Part 2

- Data Science Pipeline
- Filtering and boolean masks
- Grouping and aggregating data

## Week2.1 recap

- how to define your own functions in Python

```Python
def my_addition(parameter1, paramter2):
    
    return parameter1 + parameter2
```

- control flow and boolean logic (AND, OR logical operators)
- writing math equations in markdown cells
- intro to pandas' DataFrame
- loading data using pd.read_csv()
- basic data quality checks:

```Python
df.shape
df.info()
df.describe()
df.head()
df.tail()
df.sample()
df.columns
df.dtypes
```

- extracting 1 or several columns from a dataframe:

```Python
# 1st option:
df.age
# 2nd option:
df['age']
```

# Data Science pipeline


<img src="https://nico.nexgate.ch/images/pipeline.png" width='80%' alt="excel" />




In week 3, we will continue exploring datasets and we will start transforming data (data cleanup, data filtering, feature engineering, etc.) and we will visualize data.

## Imports

🥦 <font color='red'>TODO</font>: Execute the lines below to import the Python packages required for this notebook. (remember you can use the shortcut Shift-Enter to execute a cell in a Jupyter notebook.

In [1]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt

## Data filtering using boolean masks

A boolean mask gives a True or False for each row of data in your dataset.

If the value is True, then the row is shown otherwise, the row is no shown.

For instance, let's show only employees who work at ZHAW using a boolean mask.

First, let's re-create the employee dataframe form Week 2:

In [7]:
employee_data = {'name':['Remia','Alex','Julia','Matthias','Caroline','Georg','John'],
        'age':[23,19,37,52,46,55,61],
        'work':['Lonza','ZHAW','ZHAW','Alexion','Alexion','Sonova','ZHAW'],
        'nationality':['CH','CH','CH','DE','CH','FR','FR'],
        'savings':[45000,2300,165000,254000,420000,185000,24000],
        'checking':[3450,6500,7340,13500,12050,6540,3500]}

In [8]:
df = pd.DataFrame(employee_data)

In [17]:
#filtered_df =df.loc[(df['age'] > 20) & (df['savings'] < 40000), ['A', 'B']]
df.query("name=='Alex'")

   name  age  work nationality  savings  checking
1  Alex   19  ZHAW          CH     2300      6500

In [8]:
df

       name  age     work nationality  savings  checking
0     Remia   23    Lonza          CH    45000      3450
1      Alex   19     ZHAW          CH     2300      6500
2     Julia   37     ZHAW          CH   165000      7340
3  Matthias   52  Alexion          DE   254000     13500
4  Caroline   46  Alexion          CH   420000     12050
5     Georg   55   Sonova          FR   185000      6540
6      John   61     ZHAW          FR    24000      3500

Let's create a variable mask which will contain 1 boolean value - in other words, either True or False - for each row of the employee dataframe. 

If the employee works at ZHAW, then the value will be True for that row and otherwise, the value will be False.

In [ ]:
mask = df.work == 'ZHAW'
mask

0    False
1     True
2     True
3    False
4    False
5    False
6     True
Name: work, dtype: bool

We can then apply this mask to filter our dataframe to only show employees working at ZHAW:

In [ ]:
df[mask]

    name  age  work nationality  savings  checking
1   Alex   19  ZHAW          CH     2300      6500
2  Julia   37  ZHAW          CH   165000      7340
6   John   61  ZHAW          FR    24000      3500

NOTE: the use of a variable mask is not mandatory, we could have used the code:

```
df[df.work == 'ZHAW']
```

and it would have returned the same result.

But using a variable to define a mask allows us to check the value of the mask and also to re-use the same mask later on.

🥦 <font color='red'>TODO</font>: Show employees who older than 30.

In [9]:
# enter your code here
df[df.age > 30]

       name  age     work nationality  savings  checking
2     Julia   37     ZHAW          CH   165000      7340
3  Matthias   52  Alexion          DE   254000     13500
4  Caroline   46  Alexion          CH   420000     12050
5     Georg   55   Sonova          FR   185000      6540
6      John   61     ZHAW          FR    24000      3500

## Grouping data (similar to Excel pivot)

Let's arrange the dataset into a pivot take to organize the employees by companies.


<img src="https://nico.nexgate.ch/images/excel_pivot.png" width='80%' alt="excel" />

Reference documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

In [ ]:
df.groupby('work')

In Python, data aggregation can be done using:

```groupby()``` + 1 or several aggregation functions

Let's specifcy that we want to group our employee data by "Work" and ```count``` the number of rows for each company.

In [11]:
pivot1 = df.groupby('work').count()
pivot1

         name  age  nationality  savings  checking
work
Alexion     2    2            2        2         2
Lonza       1    1            1        1         1
Sonova      1    1            1        1         1
ZHAW        3    3            3        3         3

🥦 <font color='red'>TODO</font>: In the cell below, let's display the pivot1 dataframe only showing the column "name"

In [12]:
# add your code here
pivot1["name"]

work
Alexion    2
Lonza      1
Sonova     1
ZHAW       3
Name: name, dtype: int64

Now let's get the age average by company

In [15]:
df.age.mean()

np.float64(41.857142857142854)

🥦 <font color='red'>TODO</font>: Using groupby, show the age of the youngest employee for each company. tip: use "min"

In [17]:
# add your code here
df.groupby("work").agg({"age":"min"})

         age
work
Alexion   46
Lonza     23
Sonova    55
ZHAW      19

### Aggregation with multiple calculations

It is also possible to use different aggregation functions. 

For instance, we may count the names to get the headcount and use the mean to calculate the average savings amount per employee.

In [ ]:
df.groupby(['work']).agg({
                    'name':'count', 
                    'savings':'mean', 
                    })

         name        savings
work
Alexion     2  337000.000000
Lonza       1   45000.000000
Sonova      1  185000.000000
ZHAW        3   63766.666667

🥦 <font color='red'>TODO</font>: What would happen if we tried to use the average on the column "name"?

In [18]:
df.name.mean()

TypeError: Could not convert string 'RemiaAlexJuliaMatthiasCarolineGeorgJohn' to numeric

Finally, we can also add an additional level of grouping, say by nationality and combine it with different aggregation calculations.

In [19]:
df_work_nationality = df.groupby(['work','nationality']).agg({
                                                        'savings':'mean', 
                                                        'checking':'mean'})

df_work_nationality

                      savings  checking
work    nationality
Alexion CH           420000.0   12050.0
        DE           254000.0   13500.0
Lonza   CH            45000.0    3450.0
Sonova  FR           185000.0    6540.0
ZHAW    CH            83650.0    6920.0
        FR            24000.0    3500.0

NOTE: the result of a multi-level aggregation is a multi-level index dataframe

### Flattening of multi-index dataframe

If you want to export your multi-level index dataframe to excel, you might want to "repeat the index". In order to repeat the level 1 index (i.e. "Work"), you need to reset the index.

In [20]:
df_work_nationality.reset_index()

      work nationality   savings  checking
0  Alexion          CH  420000.0   12050.0
1  Alexion          DE  254000.0   13500.0
2    Lonza          CH   45000.0    3450.0
3   Sonova          FR  185000.0    6540.0
4     ZHAW          CH   83650.0    6920.0
5     ZHAW          FR   24000.0    3500.0

🌶️ <font color='red'>TODO</font>: Display in DataFrame the number of employees by company and total amount of savings for each company.

for Alexion, the total savings should be: 420000 + 254000 = 674000.

In [21]:
# add your code here
df.groupby("work").agg({"name":"count","savings":"sum"})

         name  savings
work
Alexion     2   674000
Lonza       1    45000
Sonova      1   185000
ZHAW        3   191300

## Using .loc vs. .iloc

In Week 1, we introduced the Pandas dataframe as the "workhorse" of data analysis in Python.

<img src="https://nico.nexgate.ch/images/excel_vs_df.jpg" width='80%' alt="excel" />

A dataframe has a lot of similarities with an Excel spreadsheet but also some differences.

An index is created when you load data using pd_read_csv() or pd.read_excel()

In Python, there are 2 ways to extracting specific rows by their indeces:

- df.loc[]
- df.iloc[] ('i' -> interger index starting from 0)

Let's use one of the columns as a labelled index.

NOTE: the values must be unique to be used as an index.

In [22]:
df.set_index(['name'],inplace=True) # note the use of inplace=True, otherwise the dataframe would not be modified

In [23]:
df

          age     work nationality  savings  checking
name
Remia      23    Lonza          CH    45000      3450
Alex       19     ZHAW          CH     2300      6500
Julia      37     ZHAW          CH   165000      7340
Matthias   52  Alexion          DE   254000     13500
Caroline   46  Alexion          CH   420000     12050
Georg      55   Sonova          FR   185000      6540
John       61     ZHAW          FR    24000      3500

In [24]:
df.loc['Julia']

age                37
work             ZHAW
nationality        CH
savings        165000
checking         7340
Name: Julia, dtype: object

In [25]:
df.iloc[2]

age                37
work             ZHAW
nationality        CH
savings        165000
checking         7340
Name: Julia, dtype: object

We can extract a slide of a dataset by provinding an index range:

- .iloc[from:to]
- .iloc[:to]
- .iloc[from:]
- .iloc[-reverve_index] , i.e. indexing from the last row

In [26]:
df.iloc[2:4]

          age     work nationality  savings  checking
name
Julia      37     ZHAW          CH   165000      7340
Matthias   52  Alexion          DE   254000     13500

In [27]:
df.iloc[:2] # first 2 rows

       age   work nationality  savings  checking
name
Remia   23  Lonza          CH    45000      3450
Alex    19   ZHAW          CH     2300      6500

🥦 <font color='red'>TODO</font>: Using ```.loc```, extract the values of "savings" and "checking" for "Georg"

In [28]:
# enter your code here
df.loc['Georg']

age                55
work           Sonova
nationality        FR
savings        185000
checking         6540
Name: Georg, dtype: object

# Checkpoints

- Know the different steps in a typical data science project
- Extract a subset of a dataset in Python
- Aggregate data in Python
- Understand dataframe indexing (loc vs. iloc)

# Additional optional labs

🌶️ <font color='red'>TODO</font>: Write the funciton head_df(df,n) which returns the first n rows of data using .iloc

In [29]:
df.head(3)

       age   work nationality  savings  checking
name
Remia   23  Lonza          CH    45000      3450
Alex    19   ZHAW          CH     2300      6500
Julia   37   ZHAW          CH   165000      7340

In [30]:
# write the code to define the funciton head_df then test it with df_head(df,3)

def df_head(df,n):
    return df.head(n)

In [31]:
df_head(df,3)

       age   work nationality  savings  checking
name
Remia   23  Lonza          CH    45000      3450
Alex    19   ZHAW          CH     2300      6500
Julia   37   ZHAW          CH   165000      7340

🌶️🌶️ <font color='red'>TODO</font>: Modify your function definition so that it prints an error message if you ask to display too many rows of data. 

For instance, df_head(df,50) should print:

"The dataframe does not have sufficient rows to display"

In [32]:
def df_head(df,n):
    # store the number of rows of your dataframe in a variable
    #...
    # check if the n parameter is less or equal to the number of rows
    if df.shape[0]>=n:
        df.head(n)
    else:
        print("The dataframe does not have sufficient rows to display")

In [34]:
df_head(df,55)

The dataframe does not have sufficient rows to display