# Start with Python - Practical exercise

# 1

In [41]:
# do not forget to load necessary packages
import numpy as np
import pandas as pd
# please be aware that the import of pandas and other relevant packages was done here and I do not need to import it again below

## 1.1
Write a function that takes two predefined lists:
- list of weights:w
- list of heights: h

and converts it to dataframe. Add appropriate names for each columns of created dataframe.

In [42]:
# predefined lists
w = [20, 30, 40, 50, 60, 70, 80]
h = [120, 130, 140, 150, 160, 170, 180]

## 1.2
Write a function to convert a NumPy array to a Pandas series.

In [43]:
# your code
df = pd.DataFrame({"width":w, "height": h} )
df

   width  height
0     20     120
1     30     130
2     40     140
3     50     150
4     60     160
5     70     170
6     80     180

# 2

## 2.1
Write a function to create and display a DataFrame from a specified dictionary data (exam_data)

Resulting dataframe index will be given by a list of labels

exam_data = {} # enter your data acording to labels length

labels = ['a', 'b', 'c', 'd']

In [56]:
labels = ['a', 'b', 'c', 'd','e','f','g','h','i']
# fill the data into this dictionary,  enter your data acording to labels length
exam_data  = {
  'name': ["Pascal","Alpha", "Beta", "Gamma","Delta","Eta","Omega","Sigma","Theta"],
  'score': np.random.randint(1,50,9),
  'attempts': [3,6,4,2,3,2,5,1,4 ],
  'qualify': [ 1,0,1,1,0,1,1,1,0]}
# your code
def convert_DataFrame(dictionary_list, label_list) -> pd.DataFrame:
    df = pd.DataFrame(dictionary_list, index=label_list)
    return df

df = convert_DataFrame(exam_data,labels)

## 2.2
Write a function to select the specified columns and rows from previously created DataFrame.

Select 'name' and 'score' columns in rows 'b', 'd', 'f', 'g'

In [58]:
# your code
df.loc[list(['b','d','g']),['name','score']]

    name  score
b  Alpha      1
d  Gamma     37
g  Omega     44

## 2.3
Then write a function to select the rows from previously created dataframe, where the score is between 15 and 20 (inclusive).

hint: pandas has between() method

In [61]:
# your code
def select_range(df, column, rangeminmax):
    return df[df[column].between(rangeminmax[0],rangeminmax[1])]

print(select_range(df,"score",(15,20)))

  name  score  attempts  qualify
f  Eta     17         2        1

# 3

## 3.1
Write a code (function is optional) to append a new row indexed as 'new_row' to previous dataframe and give values to each column that exists in it

Then delete the new row and return the changed and original dataframe.

In [62]:
# your code
def addrow(df,new_row):
    df.loc[new_row] = ['New Person', 18, 1, 0]
    return df

print(addrow(df,'z'))

         name  score  attempts  qualify
a      Pascal     49         3        1
b       Alpha      1         6        0
c        Beta      4         4        1
d       Gamma     37         2        1
e       Delta      4         3        0
f         Eta     17         2        1
g       Omega     44         5        1
h       Sigma     33         1        1
i       Theta     32         4        0
z  New Person     18         1        0

## 3.2
 Write a function to insert a new column in existing DataFrame

In [64]:
# your code
def addcolumn(df,column_name):
    df[column_name] =np.nan
    return df 

print(addcolumn(df,"NewCol"))

   nameNewCol  scoreNewCol  attemptsNewCol  qualifyNewCol  NewCol
a      Pascal           49               3              1     NaN
b       Alpha            1               6              0     NaN
c        Beta            4               4              1     NaN
d       Gamma           37               2              1     NaN
e       Delta            4               3              0     NaN
f         Eta           17               2              1     NaN
g       Omega           44               5              1     NaN
h       Sigma           33               1              1     NaN
i       Theta           32               4              0     NaN
z  New Person           18               1              0     NaN

# 4
Write a function  to count city wise number of people from a given data set (city, name of the person).

In [67]:
df = pd.DataFrame({
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']
    })
# your code
def aggrdf(df,groups, aggr_dict):
    return df.groupby(groups).agg(aggr_dict)

print(aggrdf(df,["city"],{'name' : ['count']}))

             name
            count
city
California      4
Georgia         2
Los Angeles     4

# 5

## 5.1
Display the default index and set a column as an index in a given dataframe.

In [70]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']
    })
# your code

df.index
df1= df.set_index("t_id")
df1

     school_code class            name date_Of_Birth  weight  address
t_id
t1          s001     V  Alberto Franco    15/05/2002      35  street1
t2          s002     V    Gino Mcneill    17/05/2002      32  street2
t3          s003    VI     Ryan Parkes    16/02/1999      33  street3
t4          s001    VI    Eesha Hinton    25/09/1998      30  street1
t5          s002     V    Gino Mcneill    11/05/2002      31  street2
t6          s004    VI    David Parkes    15/09/1997      32  street4

## 5.2
Create a multi-index dataframe using two columns and using an index and a selected column.

Then convert index back to column.

In [78]:
# your code
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']
    })

df1=df.set_index(['t_id','school_code'])
print(df1)
df2= df.set_index([df.index,'t_id'])
print(df2)

df3=df1.reset_index()
print(df3)

df4=df2.reset_index().drop(columns="level_0")
print(df4)

                 class            name date_Of_Birth  weight  address
t_id school_code
t1   s001            V  Alberto Franco    15/05/2002      35  street1
t2   s002            V    Gino Mcneill    17/05/2002      32  street2
t3   s003           VI     Ryan Parkes    16/02/1999      33  street3
t4   s001           VI    Eesha Hinton    25/09/1998      30  street1
t5   s002            V    Gino Mcneill    11/05/2002      31  street2
t6   s004           VI    David Parkes    15/09/1997      32  street4
       school_code class            name date_Of_Birth  weight  address
  t_id
0 t1          s001     V  Alberto Franco    15/05/2002      35  street1
1 t2          s002     V    Gino Mcneill    17/05/2002      32  street2
2 t3          s003    VI     Ryan Parkes    16/02/1999      33  street3
3 t4          s001    VI    Eesha Hinton    25/09/1998      30  street1
4 t5          s002     V    Gino Mcneill    11/05/2002      31  street2
5 t6          s004    VI    David Parkes    15/09/1997      32  street4
  t_id school_code class            name date_Of_Birth  weight  address
0   t1        s001     V  Alberto Franco    15/05/2002      35  street1
1   t2        s002     V    Gino Mcneill    17/05/2002      32  street2
2   t3        s003    VI     Ryan Parkes    16/02/1999      33  street3
3   t4        s001    VI    Eesha Hinton    25/09/1998      30  street1
4   t5        s002     V    Gino Mcneill    11/05/2002      31  street2
5   t6        s004    VI    David Parkes    15/09/1997      32  street4
  t_id school_code class            name date_Of_Birth  weight  address
0   t1        s001     V  Alberto Franco    15/05/2002      35  street1
1   t2        s002     V    Gino Mcneill    17/05/2002      32  street2
2   t3        s003    VI     Ryan Parkes    16/02/1999      33  street3
3   t4        s001    VI    Eesha Hinton    25/09/1998      30  street1
4   t5        s002     V    Gino Mcneill    11/05/2002      31  street2
5   t6        s004    VI    David Parkes    15/09/1997      32  street4

### 6
Write a function to find the indexes of rows of a specified value of a given column in a dataFrame

In [ ]:
# your code

### 7
Create a time series object that has time indexed data.
Write a function to select the dates of same year and select the dates between certain dates

hint: methods: DatetimeIndex()

In [ ]:
# your code

### 8
Write a function to check whather a day is a business day (weekday) or not.

Hint: Check pandas time series functionality of bdate_range

In [ ]:
# your code

## 9
Write a function to create a period index representing all monthly boundaries of a given year.
Also print start and end time for each period object (i.e month) in the said index.

hint: period_range,
+ check differences between datetimeindex and periodindex of pandas time series objects
+ Each record in a datetimeindex is a pd.Timestamp and represents a single point in time. Each record in a periodindex is a pd.Period and represents a time interval. A period contains a start_time and end_time attribute. They contain a lot of similar methods/attributes, and are often used interchangeably though.

In [ ]:
# your code

## 10
Write function to split the given dataframe into groups based on school code. Also check the type of GroupBy object.

In [ ]:
student_data = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']},
    index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])
# your code

### Group Work
- Import dataset of your choice and convert it to dataframe, including proper columns naming.
- Import dataset of your choice and convert it to dataframe, including proper columns naming.
- Explore groupby function of pandas
print mean values for selected groups and plot distribution of data in selected groups
- Depending on the data you selected:
  - apply one-hot/dummy encoding on selected feature
  - apply scaling of selected features
  - select k best features based on Chi2 test

Bonus:
- apply recursive feature selection using
  - from sklearn.feature_selection import RFE
- compare features selected by both methods

In [ ]:
# your code

## Homework


Write a function to apply log and box-cox transformation.
Select a adataset, convert it to pandas dataframe, select feature, display its histogram before transformation, and then after both transformations.

In [ ]:
# your code